version: '3.8'

# original source:
# https://hub.docker.com/_/mongo

services:

  mongo:
    image: mongo:4.4-bionic
    container_name: fp_mongo

    # build:
    #   context: ./mongo/.

    restart: always
    
    environment:
      MONGO_INITDB_ROOT_USERNAME: master
      MONGO_INITDB_ROOT_PASSWORD: desaster
    
    volumes:
      - ./mongo/mongo_data:/fp_data/mongo/db:rw
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

#  <----------------BackEnd-------------------->    
  webserver:
    
    image: fp:0.0.1
    container_name: fp_webserver
    
    build:
      context: ./backend/.
    ports:
      - 80:4200

    depends_on: 
      - mongo

    restart: always
    
    command: /app/docker-entrypoint.sh

networks:
  default:
    name: fp_net