version: '3.8'

# original source:
# https://hub.docker.com/_/mongo

services:

  mongo:
    image: mongo:4.4-bionic
    container_name: fp_dev_mongo
    #restart: always
    
    environment:
      #ME_CONFIG_MONGODB_URL: "mongodb://root:example@mongo:27017/"
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: [--auth]


    ports:
      - "27017:27017"

networks:
  default:
    name: fp_dev_net